### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kulikov17** [Zahak-Anjum/DeepFake-Detection-Using-Capsule-Network#1]
Hi, I'm studying neural networks and want to use them for my bachelor's degree. Please tell me it's normal that the accuracy during training is 90-100%. How true and right is this?

Is it not difficult for you to provide your processed dataset for training?

**Comment by Zahak-Anjum** [comment]
Hello @Kulikov17. Firstly, sorry for my late response. Yes it is very normal that the accuracy is 90-100% considering the problem as binary classification. It certainly takes a bit of effort to pre process the data to the requirements.
